Brief history of container
k8sp/tutorials pull request #4
Opened 2017-03-06 12:41 UTC by Yancey1989

* 容器简介
  * 容器的发展史
  * 容器和虚拟机的对比

2017-03-06 17:06 UTC, wangkuiyi approved these changes

2017-03-06 21:00 UTC, helinwang commented on Container/README.md
> +提到容器,很多人第一反应即为Docker,但实际上容器和Docker还是有一定区别的,简单来说,容器是一种轻量级的虚拟化技术,而Docker则是这种技术的一种对开发者非常友好的工具.
请把英文句号`.`都改成中文句号吧`。` ：）

2017-03-06 21:01 UTC, helinwang approved these changes
One comment, otherwise LGTM.

2017-03-07 02:25 UTC, Yancey1989 commented on Container/README.md
> +提到容器,很多人第一反应即为Docker,但实际上容器和Docker还是有一定区别的,简单来说,容器是一种轻量级的虚拟化技术,而Docker则是这种技术的一种对开发者非常友好的工具.
多谢 @helinwang 指正，已Fix.

2017-03-07 03:29 UTC, typhoonzero requested changes

2017-03-07 03:29 UTC, typhoonzero commented on Container/README.md
> +
感觉这里需要先给出一个容器的定义，1. 什么是容器，容器能解决什么问题；2. 一般容器怎么使用；3. 容器实现需要包含哪些部分（文件系统隔离，进程隔离，cgroup，网络隔离，layerfs等），然后再介绍历史。这样是否会连贯一点？

2017-03-07 03:59 UTC, Yancey1989 commented on Container/README.md
> +
> 感觉这里需要先给出一个容器的定义，1. 什么是容器，容器能解决什么问题；

有道理，在开始的部分可以加入一章节阐述**什么是容器**

>  2. 一般容器怎么使用；3. 容器实现需要包含哪些部分（文件系统隔离，进程隔离，cgroup，网络隔离，layerfs等）

由于每个阶段**容器**的概念有所不同，甚至在开始的阶段并没有明确的**容器**概念，所以第2、3部分是不是放在历史的后面，以Docker为例来介绍这些技术特性会好一些？

2017-03-07 10:01 UTC, typhoonzero commented on Container/README.md
> +容器是一种轻量级的虚拟化技术，它在进程级别对CPU、内存、文件系统、网络IO等资源进行隔离。通过容器，用户可以方便的将程序代码、配置以及运行环境进行打包。并且可以很方便的运行在不同的操作系统上运行。
虽然wikipedia上写了容器是属于虚拟化技术的一种，但这样写是否会对读者造成误解呢？

另：感觉这里加个形象一点的图片，比喻性质的图片会比较好理解？

2017-03-07 12:55 UTC, typhoonzero commented on Container/README.md
> +
明白了。

2017-03-21 08:26 UTC, typhoonzero approved these changes
LGTM

2017-03-21 08:26 UTC, merged